name: Whistle Docker build

on:
  push:  {}


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - id: debug
        run: |
          env | sort
          pwd
          ls -la

      - id: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: sessaid
          password: ${{ secrets.DH_SESSAID_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: sessaid/whistle:latest


